FROM ubuntu:22.04 as base
USER root
COPY . .
ENV TZ=Asia/Kolkata
ARG DEBIAN_FRONTEND=noninteractive

# Bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# 安装软件包
RUN apt update && apt upgrade
RUN apt install -y build-essential pkg-config libssl-dev git-all iputils-ping curl unzip

# rust 编译器
RUN rustc --version || curl https://sh.rustup.rs -sSf | /bin/sh -s -- -y

# protoc 版本替换
RUN unzip protoc-29.1-linux-x86_64.zip -d /root/.local
